name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Check GH_TOKEN
        run: echo "GH_TOKEN is set"
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Install dependencies
        run: yarn install

      - name: Build application
        run: yarn build

      - name: Publish Release
        run: yarn electron-builder --publish=always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
